name: SimpleExample

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
      fail-fast: false    
    steps:
    # Checkout
    - name: Checkout code
      uses: actions/checkout@v3
    # Build
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with: 
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: cd backend && npm ci
    - name: Build and Test
      run: cd backend && npm run build && npm run test
      continue-on-error: true
    - name: Lint
      run: cd backend && npm run lint
    - name: Message
      run: |
          "Hello ${{ github.triggering_actor }}. You pushed to ${{ github.repository }} at $(date)."."  
        
# This is a simple workflow for a python app